### ISSUE TITLE
IfcOpenShell crashes on Windows only when removing property set

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#1293]
This code snippet works fine on Linux, but apparently crashes on Windows. No idea why :)

```
import ifcopenshell
f = ifcopenshell.file()
pset = f.create_entity('IfcPropertySet', **{'GlobalId': ifcopenshell.guid.new(), 'Name': 'foo'})
f.remove(pset)
```

**Comment by aothms** [comment]
Using the latest version on my system I was not able to reproduce this. More info?

**Comment by Moult** [comment]
@aothms can you reproduce using this build? https://github.com/IfcOpenShell/IfcOpenShell/blob/v0.6.0/src/ifcblenderexport/Makefile#L29 Maybe it has been fixed since then?

**Comment by aothms** [comment]
Yes I think so, guess it has been fixed indeed here https://github.com/IfcOpenShell/IfcOpenShell/compare/b08346c..v0.6.0#diff-b040b6c3201487d58cce8bdf084d9299d961719c7f722ca4802855a2f3daa818

**Comment by Moult** [comment]
Awesome! Thanks so much! My Windows machine is broken so I'll test it whenever I do get the chance and close this issue.

**Comment by Moult** [comment]
Closing bug, assuming fixed.

**Comment by cesnik-jure** [comment]
With the latest ifcopenshell deleting a pset still crashes.
Just trying to get around this problem...

**Comment by aothms** [comment]
@cesnik-jure can you post a minimal example to reproduce your issue

**Comment by cesnik-jure** [comment]
This is a part of a larger script, but to sum it up:

import ifcopenshell
file_IFC = ifcopenshell.open(file)
products = file_IFC.by_type('IfcElement')
psets_delete = {'2TDK_Klasifikacija', '2TDK_Lokacija'}

for ifc_product in products:
    for definition in ifc_product.IsDefinedBy:
        if definition.is_a('IfcRelDefinesByProperties'):
            ifc_pset = definition.RelatingPropertyDefinition

            for excel_pset_delete in psets_delete:
                if ifc_pset.Name == excel_pset_delete:
                    file_IFC.remove(ifc_pset)

IFC file to parse is attached in TXT.
[2TDK_LEA_PZI_PLA_T3D_HBV_GCP_DI_008.txt](https://github.com/IfcOpenShell/IfcOpenShell/files/6198749/2TDK_LEA_PZI_PLA_T3D_HBV_GCP_DI_008.txt)

**Comment by aothms** [comment]
@cesnik-jure in this way you're probably deleting the same pset multiple times as elements can share the same pset. Either add all psets to a `set` first so that you eliminate the duplicates. Or instead of iterating over the products, why don't you start with by_type(IfcPropertySet).

**Comment by cesnik-jure** [comment]
@aothms I've tested a bit more and removing Psets works. I'm still not completely sure why my code is not working as there are not references to the same Pset, but I'll change the code so this problem won't be present.
