### ISSUE TITLE
BlenderBIM: error ifc export after manual mesh merge

### ISSUE THREAD

**Issue by ay-ex** [IfcOpenShell/IfcOpenShell#2851]
In a model with elements very similar to shown in https://github.com/IfcOpenShell/IfcOpenShell/issues/2847 
I followed that recipe and merged, set to tessellated 
some triangular IfcSlab SweptSolid subelements 
from one Slab: 

```python
def join_tesselated():
	selected_elems = C.selected_objects
	if len(selected_elems) > 0:
		bpy.ops.object.join()
	selected_elems = C.selected_objects
	if len(selected_elems) == 1:
		elem = C.selected_objects[0]
		bpy.ops.bim.update_representation(
			obj=elem.name,
			ifc_representation_class="IfcTesselatedFaceSet",
		)
	else:
		print("selection does not meet criteria")
		
join_tesselated()
```

then removed it from the aggregates and 
deleted the empty container and empty node. 

For a few this worked fine, and I could re-export afterwards, 
but for most elements I get this error when trying to export:

```
Python: Traceback (most recent call last):
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\project\operator.py", line 829, in invoke
    return self.execute(context)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\project\operator.py", line 842, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\ifc.py", line 427, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\project\operator.py", line 873, in _execute
    ifc_exporter.export()
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\export_ifc.py", line 49, in export
    self.sync_all_objects()
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\export_ifc.py", line 115, in sync_all_objects
    result = self.sync_object_material(obj)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\export_ifc.py", line 146, in sync_object_material
    bpy.ops.bim.update_representation(obj=obj.name)
  File "C:\ProgramData\portable\blender-3.4.1\3.4\scripts\modules\bpy\ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 41, in execute
    IfcStore.execute_ifc_operator(self, context)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\ifc.py", line 427, in execute_ifc_operator
    result = getattr(operator, "_execute")(context)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 178, in _execute
    self.update_obj_mesh_representation(context, obj)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\geometry\operator.py", line 238, in update_obj_mesh_representation
    new_representation = ifcopenshell.api.run("geometry.add_representation", self.file, **representation_data)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\__init__.py", line 66, in run
    result = usecase_class(ifc_file, **settings).execute()
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 69, in execute
    return self.create_model_representation()
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 122, in create_model_representation
    return self.create_variable_representation()
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 237, in create_variable_representation
    return self.create_arbitrary_void_extrusion_representation()
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 510, in create_arbitrary_void_extrusion_representation
    return self.create_arbitrary_extrusion_representation()
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\libs\site\packages\ifcopenshell\api\geometry\add_representation.py", line 498, in create_arbitrary_extrusion_representation
    item = helper.create_extruded_area_solid(self.settings["geometry"], indices["extrusion"], profile_def)
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\geometry\helper.py", line 495, in create_extruded_area_solid
    direction = self.get_extrusion_direction(mesh, extrusion_indices, profile_def["curve_ucs"])
  File "C:\Users\user.name\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blenderbim\bim\module\geometry\helper.py", line 637, in get_extrusion_direction
    curve_ucs["center"] + (mesh.vertices[extrusion_indices[1]].co - mesh.vertices[extrusion_indices[0]].co)
TypeError: 'NoneType' object is not subscriptable
Location: C:\ProgramData\portable\blender-3.4.1\3.4\scripts\modules\bpy\ops.py:113
```

Which seems strange to me. 
Among other things it complains about "create_extruded_area_solid", 
but I thought I just turned the combined mesh into a IfcTesselatedFaceSet. (?)
Maybe @Moult any ideas?

**Comment by Moult** [comment]
How are you deleting objects? Note that (assuming you are on the latest) you should use bim.override_object_delete, which is not the same as the normal Blender delete.

**Comment by ay-ex** [comment]
Right, I am on latest-ish (usually 1-day behind). 
I see. Thank you for the hint about deleting. 
I was indeed using the regular blender delete - I will try with `bim.override_object_delete` and give feedback.

**Comment by ay-ex** [comment]
Oh ok , I was under the impression I could call `bim.override_object_delete` from Python. 
But if I read it correctly in ifcopenshell repo, it is actually an override to pressing `x` or `del` - 
which is what I used, before the error on reexport showed up.

**Comment by Moult** [comment]
You can call bim.override_object_delete from Python, right? At least we do in the test suites. That should be what you should use whenever you are deleting Blender objects that are linked to IFC.

**Comment by ay-ex** [comment]
Unfortunately it gives me the same error though. 🤔

**Comment by ay-ex** [comment]
Unfortunately not possible, but maybe we can do a screen share to figure it out?

**Comment by Moult** [comment]
Sure, tomorrow? It's 10pm now.

**Comment by Moult** [comment]
Bump @aothms

**Comment by ay-ex** [comment]
@Moult : I can confirm the export error is gone. 👍

**Comment by Moult** [comment]
Cheers, we'll keep this open until @aothms gets a chance to look at the triangle.ifc to explain why we don't get 6 vertices :)

**Comment by aothms** [comment]
I don't know... I checked that the shape we feed to the occt mesher is what we expect:

(interlude, this is what I was talking about with the huge number of indirections in the occt data model [no critique, just observation] as compared to a mesh-based kernel)

![afbeelding](https://user-images.githubusercontent.com/1096535/230761063-93ab6aac-365a-4e4b-ae72-036940dfaef6.png)

Solid with 5 faces where the bottom face has exterior bound with 3 edges.

The result indeed contains a number of close points:

```
array([[ 5.14262327e+00,  8.23348494e+00,  3.94892940e-01],
       [ 5.14262327e+00,  8.23348494e+00,  3.48929404e-02],
       [-5.32907052e-15,  5.14262327e+00,  8.88178420e-16],
       [-5.77315973e-15,  5.14262327e+00,  3.60000000e-01],
       [ 7.18333797e+00,  4.83811238e+00,  4.86977303e-02],
       [ 7.18333797e+00,  4.83811238e+00,  4.08697730e-01],
       [ 5.14262327e+00,  8.23348494e+00,  3.48929404e-02],
       [-5.77315973e-15,  5.14262327e+00,  8.98586761e-16],
       [ 7.18333797e+00,  4.83811238e+00,  4.86977303e-02]])
```

For example the first two rows are quite close (but also not **that** close). I'd still say it's probably due to the fact that in an extrusion OCCT expresses the top face as a translation of the bottom face and somehow in the process due to the additional matrix multiplication, there is a discrepancy.

Does anybody know what's the situation in which this occurs. Is it in extruded triangles, or extrusions with a rotation, random, always?

If I would have to guess it

**Comment by Moult** [comment]
Absolutely no idea, but it happens very frequently in @ay-ex 's test model. If it helps we can extract more of these objects from his model?

**Comment by aothms** [comment]
Maybe let's do that and have a look, if you think it's important enough...

**Comment by ay-ex** [comment]
Recently we had a submission, where - as usual - we tried to patch our ifcs 
in the above described way. Most of them worked fine ☺️,  but two of them 
run into the same above problem/error.
I tested it on the blender 3.6 / bbim 230517 (for which this script was written)
as well on blender 4.0 / bbim 240119, but the behavior is the same.
The smaller of the two files is ~34mb. Unfortunately the error shows up only 
after blender/blenderbim has been chewing on it for ~28minutes. 

(Side note: When I tried to excerpt single groups of triangles via ifcpatch extract, 
I run into Python recursion error. Python standard recursion limit: 1000.
I tested it with rec_limit at 1500, 2500 (same error) and 9999 (blender crash)
@Moult: I think we ran into that already some other day..  )

@aothms , @Moult : Is there something I can help with, for the progress of this issue? 🙂 
@Moult a screenshare maybe?

**Comment by ay-ex** [comment]
Ah wait, if we merged the vertices, so that the vertex count aligns what we should have (6 vertices per extruded triangle), 
then it should work, I assume. So I will try to find out how to merge the corner vertices in blender. 🙂

**Comment by falken10vdl** [comment]
@ay-ex . Did you manage to get those vertices merged? What is the current status?
Thanks!

**Comment by ay-ex** [comment]
@falken10vdl unfortunately not. 
but fortunately the last few models we patched this way did not have this issue.

**Comment by falken10vdl** [comment]
@ay-ex so what do we do with this issue :)

**Comment by BIMvoice** [comment]
This still reproduces on v0.8.0, though not with the original `triangle.ifc` anymore: its duplicate vertices are near-exact, so the `remove_doubles(0.0001)` added since 2023 already merges them and it exports as a clean extrusion. The crash survives whenever the duplicates are further apart than that tolerance (or the mesh genuinely isn't an extrusion): `detect_extrusion_edge()` returns `None` and the export dies on the `None` subscript in `get_extrusion_direction()`.

Fixed in #8336. When the arbitrary-profile detection fails, Bonsai now welds the coincident duplicate corner vertices and retries, so the element stays a proper parametric `IfcExtrudedAreaSolid` (verified with a synthetic 9-vertex triangular prism whose corners are 1e-3 apart). The weld only merges vertices that don't share an edge, so a thin extrusion's short edges are never collapsed and #3053 doesn't regress (verified with a 0.4 mm slab). If the mesh genuinely isn't an extrusion, it now falls back to a tessellated `IfcPolygonalFaceSet` that preserves the geometry, instead of crashing.
