### ISSUE TITLE
Segfault 11 on IfcWall (see example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#288]
**Steps to reproduce:**
1. Convert [wall__segfault.ifc.zip](https://github.com/IfcOpenShell/IfcOpenShell/files/1437686/wall__segfault.ifc.zip)
2. Experience `Segmentation fault: 11`

This happens on both of these versions of IfcOpenShell:
1. `IfcOpenShell IFC2X3 IfcConvert 0.5.0-dev (OCC 7.2.0)` – built from commit 8d0c95a9391f887e262e95cec646dca2c59ceadf
2. `IfcOpenShell IFC2X3 IfcConvert 0.5.0-dev (OCC 6.9.1.oce-0.18)`

The file opens without warnings in Solibri and DDS viewer:
<img width="686" alt="screenshot__solibri" src="https://user-images.githubusercontent.com/4601554/32326109-e35719ae-bfd1-11e7-8d63-2b78e979ab0a.png">

**Comment by aothms** [comment]
Thanks for the report, I committed something for this: 148432c011d63bafabb694fa1ca07ac533f6e6ae

It seems the tolerance adjustments for OCCT versions prior to 6.9.1 better be disabled on later versions as per fuzziness argument now effective on boolean ops.

Let me know if you encounter any further issues.

Kind regards,
Thomas

**Comment by johanrd** [comment]
Hi Thomas. Thanks! Seems like a reasonable fix. 

However, when converting with `IfcOpenShell IFC2X3 IfcConvert 0.5.0-dev (OCC 7.2.0)` – built from commit 6463690a8b76451e6cfeded340d75f05119f5ffd – we still get a segfault. What version of `OCC` did you use when converting? 

thanks,
johan

**Comment by aothms** [comment]
> What version of OCC did you use when converting?

To be honest, I used 7.1.0 on Windows. I could reproduce the crash with that.

I'll have another look with the exact configuration you posted.

**Comment by johanrd** [comment]
Update: I have now tried with 5d0c04a, and I am still able to reproduce on both `OCCT v7.2.0` and `OCCT v7.1.0` on Linux Debian.

**Comment by aothms** [comment]
This appears to be a similar geometrical issue to #297. The profile of the rectangular opening self-intersects as `#80` is on the edge between `#76` and `#77` (or at least close to it).

The consequence of a segfault is more serious of course and is because the geometry takes part in a boolean operation in which case OCCT is generally quite unforgiving in terms of invalid input.

Also `#75` and `#76` are quite close to each other. Removing `#76` fixes the segfault but still doesn't succesfully apply the subtraction probably because due to the self intersection OCCT has issues figuring out the orientation.

The generic shape healing as investigated in the case of #297 (but then applied on IfcPolyline instead of Loop) does not seem to work in this case.

~~~
#74 = IFCPOLYLINE((#75, #76, #77, #78, #79, #80, #75));
#75 = IFCCARTESIANPOINT((-1293.21909900983, -706.575936994));
#76 = IFCCARTESIANPOINT((-1293.21909900983, -706.848126014006));
#77 = IFCCARTESIANPOINT((1156.60954940753, -706.848126013998));
#78 = IFCCARTESIANPOINT((1156.60954940752, 1413.424063008));
#79 = IFCCARTESIANPOINT((136.609549602319, 1413.424063008));
#80 = IFCCARTESIANPOINT((136.609549602342, -706.575936994));
~~~

**Comment by aothms** [comment]
Note to self: investigate `ShapeFix_Wire::FixNonAdjacentIntersectingEdgesMode` for fixing non-adjacent intersecting edges.

**Comment by johanrd** [comment]
Nice! I can verify that this segfault is fixed by commit 6563467 :tada:

**Comment by aothms** [comment]
Great, thanks for checking
