### ISSUE TITLE
[BlenderBIM] - Idea - Duplicating IfcElementAssembly

### ISSUE THREAD

**Issue by brunoperdigao** [IfcOpenShell/IfcOpenShell#3068]
I created two operators to deal with IfcElementAssembly. The first one copies the element and all its parts in order to create a copy of the whole assembly. The second updates changes made in the original assembly to the other copies. The GIF below shows an example:
![GIF 26-04-2023 13-21-30](https://user-images.githubusercontent.com/57102715/234859484-93443086-782b-4f28-a087-57c7de76dd3d.gif)

I'd like to make sure that it makes sense to implement this feature before creating a PR. The code is still messy, and I'd have to organize a few things before submitting.

If so, a few topics for future development:
1. Where would this go in the UI? The copying operator works like a shift+d and can be used with a keymap.
2. Other operators should be created for selecting the parent objects and to break the link with the parent.
3. This uses most of the same logic as IfcArray, so #3063  is an issue for this too.
4. This could be extended to implement IfcArray for IfcElementAssembly? This is a whole new topic, but I think the only reason why the array is not possible in assembly elements is because the array UI is stored inside blender's modifiers panel, and blender hides them when an empty object is selected.

**Comment by brunoperdigao** [comment]
related: https://community.osarch.org/discussion/comment/15536/#Comment_15536

**Comment by brunoperdigao** [comment]
Hi @Moult,

I'm getting back to this after a while, and I have this branch working: https://github.com/brunoperdigao/IfcOpenShell/tree/duplicate-assembly2
Here's a demo;
![GIF 19-06-2023 17-20-33](https://github.com/IfcOpenShell/IfcOpenShell/assets/57102715/e6d306a2-c5a9-44b1-bb19-efa8cf47868b)


However, I realized that this branch was outdated, and I started working in a new branch that I synced with the main development yesterday. I'm getting this strange behavior where it successfully creates the aggregate but doesn't create a new Blender collection for the new objects:
![GIF 19-06-2023 17-17-35](https://github.com/IfcOpenShell/IfcOpenShell/assets/57102715/7b11218a-597d-4f76-bb95-ad174d5568e4)




I can't figure out what change is causing this issue. Any ideas? Here is the new branch: https://github.com/brunoperdigao/IfcOpenShell/tree/duplicate-aggregate

**Comment by theoryshaw** [comment]
I have no clue, but could it be related to this commit?
https://github.com/IfcOpenShell/IfcOpenShell/commit/586707dd28d51d2d5f1bdc931a40e199e3f2f98c

**Comment by brunoperdigao** [comment]
Nice hint @theoryshaw!

For reference, after copying an aggregate object the `BIMObjectProperties.collection` was not being cleared, so I would end up going to the same collection as the old object. My solution was to insert `BIMObjectProperties.collection = None`. I don't know if this is the right approach or if this should be addressed in another part of the code, but works for now.

I'll create a PR soon

**Comment by brunoperdigao** [comment]
Hi @Moult @Andrej730,
I'm refactoring the code for the "duplicate aggregate" operator. It was built with a lot of code duplication from the "OverrideDuplicateMove" and now I want it to call `OverrideDuplicateMove.execute_ifc_duplicate_operator` directly. 
The thing is that there are behaviors that I want to build for "duplicate aggregate" that I think could be implemented in "OverrideDuplicateMove" as well, such as: #3770, #2187, #3769. I'm thinking of creating a PR to implement these functionalities with `shift+d`. What do you guys think?

**Comment by brunoperdigao** [comment]
I'm also trying a different approach for "duplicate aggregate", using IfcGroups, that would introduce some breaking changes. Since, @theoryshaw is using this feature in a live project, what would be the best way for me to develop this new approach without hurting his workflow? Should I create another operator and have them both existing for a while?

**Comment by Andrej730** [comment]
@brunoperdigao yeah, makes sense. I've been noticing there were some common code in duplicate aggregate and it would be nice to connect it to the same place, where it's possible. 
Have been noticing #2187 for awhile now too, didn't know we had an issue for it already 😁

> Should I create another operator and have them both existing for a while?

Don't know, depends if old apporach will still have any benefits after new one is implemented. If new approach will be just better then perhaps some small script/patch to upgrade ifc model could help.

**Comment by brunoperdigao** [comment]
@Andrej730 Got it. So, I'll start working on the improvements on `OverrideDuplicateMove`.

**Comment by theoryshaw** [comment]
Just another thought. It might be a good idea that if an object inside an aggregate is duplicated (shift+d), that it removes the `BBIM_Aggregate_Data' pset. Similar to how the 'BBIM_Array' pset is removed when an object from an array is duplicated (shift+d).

from: https://community.osarch.org/discussion/comment/17882/#Comment_17882
