### ISSUE TITLE
Regression: segfault on kitchen (example file)

### ISSUE THREAD

**Issue by johanrd** [IfcOpenShell/IfcOpenShell#376]
**Steps to reproduce:**
1. Convert [376--kitchen--segfault--augmented.ifc](https://github.com/IfcOpenShell/files/blob/master/376--kitchen--segfault--augmented.ifc) with c748c8d (OCCT v7.2.0)
2. Experience segfault: 
```FATAL: An error occured, status code 139.```

There are no errors when converting with e87a1a0 (OCCT v7.2.0), so this is seemingly a recent regression:
<img width="300" alt="screen shot 2018-04-23 at 16 59 47" src="https://user-images.githubusercontent.com/4601554/39134811-d04f7eb4-4717-11e8-97df-b4aaaca4e3ea.png">

**Comment by aothms** [comment]
Ok, I fixed this by making the tolerance for intersection detection a bit more conservative. The underlying problem is a bit more intricate, because due to geometric tolerance intersecting edges/vertices are cylinders and spheres, now any intersection is chosen, but it should be the intersection on an edge with intersection point closest to the domain of the curve. Due to the reduced tolerance this is not likely to result into issues anymore.

8ffc12e6cd5cb93430f055370ba0c80f84789c6b

**Comment by johanrd** [comment]
Hmm, yes, this do seem to fix the issue for this kitchen, and also the socket mentioned in #377.

However, this reduced tolerance seem to affect the fixes for #288, the beam in #330, #342, and #367, which all seem to be reproducible again. So I guess you have a point regarding the underlying problem still being there.

**Comment by aothms** [comment]
Ok, reverting the tolerance on point proximity seems to help a bit. I'll see if I can run the conversions on Travis at every commit.

**Comment by aothms** [comment]
589f4bda2ecdd02366225b541376576c04a2da27

**Comment by aothms** [comment]
With this partial revert in 589f4bd only #342 remains open. But I didn't look into that one in detail yet.

**Comment by johanrd** [comment]
Reopening, as this file segfaults on `OCCT 7.4.0` (with e37c882fe2ca783f09667df983e7f83d707cd364)

**Comment by johanrd** [comment]
Closing, as this does not segfault on `OCCT 7.5.0`
