### ISSUE TITLE
IfcTeste Flag Failed Entities

### ISSUE THREAD

**Issue by BIMvoice** [IfcOpenShell/IfcOpenShell#4062]
Hi guys!

This new feature is amazing, well done (@c4rlosdias ?)!

There is something I am missing already, and that is the cursor to select all the elements in an error, like it was before this update. And I would also like to have the list of all the elements in that menu, so I can switch between them from there.

TLDR: I would like to have the Flag Failed Entities feature combined with everything from before if possible.

**Comment by BIMvoice** [comment]
@c4rlosdias I really miss the previous functionality. It was great to be able to see the full list of errors and to be able to select the specific objects. I find the current functionality much more limiting for quick navigation over the issues. Do you plan to make any other changes in the future?

**Comment by c4rlosdias** [comment]
Sorry for the delay in replying. This feature should be working, let's take a look. Thank you.

**Comment by c4rlosdias** [comment]
made pull request #4095

**Comment by BIMvoice** [comment]
Thank you very much @c4rlosdias . I'll check it out!

**Comment by BIMvoice** [comment]
It's still not working as before. All the errors are shown in just 1 occurrence, so I cannot choose only one error in only 1 element. And the cursor symbol is miss, so I cannot select in the model the elements I am interested in. I really miss the previous functionality since I'm using this at work.

![image](https://github.com/IfcOpenShell/IfcOpenShell/assets/139251053/11b8b2af-3583-48d1-b86c-ba2f63f982f6)

**Comment by c4rlosdias** [comment]
The pull request has not yet been approved for merge
