### ISSUE TITLE
Non-planar curved AdvancedBrep support in v0.8.0

### ISSUE THREAD

**Issue by Moult** [IfcOpenShell/IfcOpenShell#4895]
The segfault is now fixed, but I get empty verts consistently for any of those "broken" geometries. For example with the `rac.ifc`:

```python
import ifcopenshell
import ifcopenshell.geom

ifc_file = ifcopenshell.open("/home/dion/rac.ifc")
settings = ifcopenshell.geom.settings()
element = ifc_file.by_id(598) # #598=IfcShapeRepresentation(#670,'Body','AdvancedBrep',(#597))
result = ifcopenshell.geom.create_shape(settings, element)
print(result.verts) # Empty
```

_Originally posted by @Moult in https://github.com/IfcOpenShell/IfcOpenShell/issues/4832#issuecomment-2178308608_

**Comment by aothms** [comment]
Ok, planar advanced brep should work a bit better again. Curved geometry still needs some work.

Notes for the curiously inclined:

- First of all I had no idea that Revit started emitting advanced brep for polyhedral meshes, why?
- Secondly, it does so a bit weirdly in the sense that emits IfcTrimmedCurve as a underlying edge curves as opposed to the untrimmed mathematical base curves. This is kind of bad practice because you trim twice, both in the geometry as well in the topology, there are notes in OCCT you shouldn't do this. I assume this applies to other geom libraries as well. In our case this means the underlying edge geometry is mapped in the taxonomy to an edge as well, which meant it was approximated by a nurbs curve when fed to the edge geometry. The code has been changed to unwrap trimmed curves to their bases, but I still need to double check for sense and orientation on periodical curves, because trimmed curve can affect those, so this information needs to be retained when unwrapping.

**Comment by Moult** [comment]
Hooray! Confirming this is fixed for planar BReps.

Here's some further reading: https://github.com/Autodesk/revit-ifc/issues/480

Here's a test file for curved breps. Right now I get nothing (as you predict).

[basin-advanced-brep.txt](https://github.com/user-attachments/files/15962242/basin-advanced-brep.txt)

**Comment by Moult** [comment]
I've attached three more samples of AdvancedBReps which fail which might help: a pipe fitting (right now basically every pipe fitting is broken), a stack terminal, and a boiler.

[more-advanced-brep.txt](https://github.com/user-attachments/files/15963338/more-advanced-brep.txt)

**Comment by aothms** [comment]
I recommend to stick to v0.7 for the time being if this is your use case. Technically speaking though this issue only affects reading, not writing, which is mostly unaffected by the changes in v0.8. A sphere is actually one of the elements that might still face issues even in v0.7, because it requires seam curves and vertex loops (the topology for an advanced brep sphere is actually fairly complex) and we never really worked on it, because they are almost never exchanged.

**Comment by aothms** [comment]
Some progress, but the basin from the spec still doesn't render.

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/a8b81b65-eb7d-4a70-a395-dbaec8ffa026)
![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/d57611cf-0b58-47cb-bcc5-bd70162ddf38)
![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/f2889195-4561-4efe-a166-ca91360aee04)
![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/be5cc623-7b5d-4910-a2f9-0cb95ff1977f)

**Comment by aothms** [comment]
Ok, that was easy.

![afbeelding](https://github.com/IfcOpenShell/IfcOpenShell/assets/1096535/8e0545f8-4d47-4f66-8b46-b234e8438f0e)

**Comment by Moult** [comment]
Was there a regression recently? I'm getting this kind of cute snail artifact again (I thought I saw this before in a later OCCT version):

Also here is another sample file. 
[heater.ifc.txt](https://github.com/user-attachments/files/16137296/heater.ifc.txt)

The (planar?) clearance zone seems to be glitching out, the the boiler now has some sort of cylinder covering it (not sure if that's right or not).

![2024-07-09-133000_933x745_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/84bfe1ac-0005-428f-9c9a-d123a501f72f)
![2024-07-09-132941_447x487_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/235bdc2a-b7ed-429f-a619-f20c4af4c051)


![2024-07-09-132102_288x311_scrot](https://github.com/IfcOpenShell/IfcOpenShell/assets/88302/1476c0f9-05cb-4ac1-a408-6cc332ab6ccc)

**Comment by aothms** [comment]
Cute snail artefact I thought was never resolved, but I can't find the issue we had for that.

Triangular artefact resolved.

**Comment by Moult** [comment]
See #3559 for snail history :) does that help?

**Comment by aothms** [comment]
Thanks I isolated it into a new issue: https://github.com/IfcOpenShell/IfcOpenShell/issues/5064

**Comment by Moult** [comment]
Cheers, I no longer see snails when compiled locally :) Marking as fixed!
 
![2024-07-25-172538_632x519_scrot](https://github.com/user-attachments/assets/bc0fa259-b933-41eb-8cf0-8c48c800837c)
